import { useState } from 'react';
import { ArrowUpRight, History } from 'lucide-react';
import { Link } from 'wouter';
import { useListActivity } from '@workspace/api-client-react';
import { useI18n } from '@/i18n';
const tones=['all','positive','neutral','warning','danger'] as const;
export default function ActivityPage(){
 const {t}=useI18n();const [tone,setTone]=useState<(typeof tones)[number]>('all');const activity=useListActivity();
 const items=(activity.data??[]).filter(a=>tone==='all'||a.tone===tone);
 return <div className="mx-auto max-w-5xl animate-rise-in"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#1DE9B6]">PITRUST / LEDGER</p><h1 className="mt-3 font-['Syne'] text-4xl sm:text-5xl">{t('navigation.activity')}<span className="text-[#00C853]">.</span></h1><p className="mt-3 text-sm text-[#94ab9a]">{t('landing.recentActivity')}</p><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{tones.map(value=><button key={value} onClick={()=>setTone(value)} className={`rounded-full border px-4 py-2 text-xs capitalize ${tone===value?'border-[#00C853] bg-[#193222] text-[#1DE9B6]':'border-[#34473b] text-[#9cae9d]'}`} data-testid={`button-filter-${value}`}>{value==='all'?t('common.all'):value}</button>)}</div>{activity.isLoading?<div className="skeleton mt-8 h-96 rounded-xl"/>:activity.isError?<div className="mt-8 rounded-xl border border-[#574039] p-6 text-sm">{t('errors.network')} <button onClick={()=>activity.refetch()} className="ms-4 text-[#1DE9B6]" data-testid="button-retry-activity">{t('common.retry')}</button></div>:!items.length?<div className="mt-8 rounded-xl border border-dashed border-[#3a503e] p-16 text-center"><History className="mx-auto text-[#1DE9B6]"/><p className="mt-4 text-sm text-[#9caf9d]">{t('search.noResults')}</p></div>:<div className="mt-7 divide-y divide-[#344139] overflow-hidden rounded-xl border border-[#344139] bg-[#1A1A1A]">{items.map(event=><article key={event.id} className="flex gap-5 p-6" data-testid={`activity-${event.id}`}><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#00C853]"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold">{event.title}</h2><time className="font-mono text-xs text-[#8ca08e]">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-2 text-sm text-[#a1b3a4]">{event.description}</p><div className="mt-4 flex items-center justify-between text-xs"><span className="font-mono text-[#7f9a87]">{event.actor}</span><Link href={`/contracts/${event.contractId}`} className="flex items-center gap-1 text-[#1DE9B6]" data-testid={`link-activity-${event.id}`}>{t('navigation.contracts')}<ArrowUpRight size={14}/></Link></div></div></article>)}</div>}</div>;
}