import { useState, type FormEvent } from 'react';
import { useUser } from '@clerk/react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, FileCheck2, LockKeyhole, MessageCircle, Package, Scale, ShieldCheck, WalletCards } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { getGetContractQueryKey, getGetDashboardSummaryQueryKey, getGetTestnetWalletQueryKey, getListActivityQueryKey, getListContractsQueryKey, getListSignaturesQueryKey, useConfirmDelivery, useCreateContractPaymentIntent, useFundContract, useGetContract, useGetTestnetWallet, useListSignatures, useReleaseContractToTestnetWallet, useReleaseFunds, useSignContract, useSubmitDelivery, type Contract, type DeliveryInput } from '@workspace/api-client-react';
import ContractEvidence from '@/components/contract-evidence';
import { usePiPayment } from '@/hooks/use-pi-payment';
import { usePiAppSession } from '@/lib/pi-app-session';
import { useI18n, type TranslationKey } from '@/i18n';
import { formatDate, formatMoney } from '@/lib/escrow';
import { PI_SANDBOX } from '@/lib/pi-sdk';

const steps=['draft','awaiting_funding','funded','in_delivery','completed'] as const;
const statusKeys:Record<string,TranslationKey>={draft:'status.draft',awaiting_funding:'status.awaitingPayment',funded:'status.funded',in_delivery:'status.inProgress',completed:'status.completed',disputed:'status.disputed',resolved:'status.resolved',cancelled:'status.cancelled'};
const fields:Record<string,{label:TranslationKey;key:keyof DeliveryInput}[]>={
 digital:[{label:'contractWizard.deliverables',key:'digitalLinks'}],
 shippable:[{label:'delivery.carrier',key:'carrier'},{label:'delivery.trackingNumber',key:'trackingNumber'}],
 local_property:[{label:'contractWizard.propertyAddress',key:'physicalAddress'},{label:'contractWizard.permitOrReference',key:'deedReference'},{label:'contractWizard.permitOrReference',key:'titleReference'},{label:'contractWizard.propertyAddress',key:'mapUrl'}],
 custom_terms:[{label:'contractWizard.milestones',key:'goals'}],
};
function contractInfo(data:Contract){
  const raw=data as Contract & {pipeline?:string;metadata?:Record<string,unknown>;buyerId?:string|null;sellerId?:string|null};
  return {pipeline:raw.pipeline,metadata:raw.metadata,buyerId:raw.buyerId,sellerId:raw.sellerId};
}

function sandboxError(error: unknown): string | undefined {
  const candidate = error as { response?: { data?: unknown }; data?: unknown } | undefined;
  const value = candidate?.response?.data ?? candidate?.data;
  if (!value || typeof value !== 'object') return undefined;
  const reason = (value as Record<string, unknown>).reason;
  return typeof reason === 'string' ? reason : undefined;
}

function SandboxContractActions({ id, data, role, refresh }: { id: string; data: Contract; role: 'buyer' | 'seller' | 'unknown'; refresh: () => void }) {
  const { t } = useI18n();
  const wallet = useGetTestnetWallet({ query: { queryKey: getGetTestnetWalletQueryKey(), enabled: PI_SANDBOX, refetchInterval: 30000 } });
  const fund = useFundContract();
  const release = useReleaseContractToTestnetWallet();
  const [error, setError] = useState('');
  const canFund = role === 'buyer' && data.status === 'awaiting_funding';
  const canRelease = role === 'buyer' && data.status === 'in_delivery';
  const runFund = () => {
    setError('');
    fund.mutate({ id }, { onSuccess: refresh, onError: (reason) => setError(sandboxError(reason) === 'insufficient_balance' ? t('errors.internalInsufficientBalance') : t('errors.internalFundingFailed')) });
  };
  const runRelease = () => {
    setError('');
    release.mutate({ id }, { onSuccess: refresh, onError: () => setError(t('errors.internalReleaseFailed')) });
  };
  return <section className="rounded-xl border border-[#2f5c45] bg-[#14251b] p-6 sm:p-8" data-testid="card-internal-funding">
    <div className="flex items-center gap-3"><WalletCards className="text-[#1DE9B6]" /><h2 className="font-['Syne'] text-xl">{t('escrow.fundEscrow')}</h2></div>
    <div className="mt-4 flex flex-wrap items-baseline justify-between gap-3"><p className="text-sm leading-6 text-[#a6c2ae]">{t('wallet.sandboxNotice')}</p>{wallet.data && <p className="font-mono text-sm text-[#8ff0c9]">{wallet.data.balance.toLocaleString(undefined, { maximumFractionDigits: 8 })} Test-Pi</p>}</div>
    {wallet.isError && <p className="mt-4 text-sm text-[#ff9c91]" role="alert">{t('errors.network')}</p>}
    {canFund && <button onClick={runFund} disabled={fund.isPending || wallet.isLoading || wallet.isError || !wallet.data} className="mt-6 rounded-lg bg-[#00C853] px-5 py-3 text-sm font-bold text-[#07150b] disabled:opacity-45" data-testid="button-fund-internal">{fund.isPending ? t('common.loading') : t('escrow.fundEscrow')}</button>}
    {canRelease && <button onClick={runRelease} disabled={release.isPending} className="mt-6 rounded-lg bg-[#00C853] px-5 py-3 text-sm font-bold text-[#07150b] disabled:opacity-45" data-testid="button-release-internal">{release.isPending ? t('common.loading') : t('escrow.releasePayment')}</button>}
    {!canFund && !canRelease && <p className="mt-5 text-sm text-[#8da997]">{data.status === 'completed' ? t('escrow.paymentReleased') : t('escrow.fundsHeldSecurely')}</p>}
    {error && <p className="mt-3 text-sm text-[#ff9c91]" role="alert" data-testid="alert-internal-funding">{error}</p>}
  </section>;
}

export default function ContractDetail(){
  const {id=''}=useParams<{id:string}>();const {t,direction}=useI18n();const {user}=useUser();const {accountId: piAccountId}=usePiAppSession();const qc=useQueryClient();
  const contract=useGetContract(id,{query:{enabled:!!id,queryKey:getGetContractQueryKey(id),refetchInterval:10000}});
  const signatures=useListSignatures(id,{query:{enabled:!!id,queryKey:getListSignaturesQueryKey(id)}});
  const intent=useCreateContractPaymentIntent();const deliver=useSubmitDelivery();const confirmDelivery=useConfirmDelivery();const sign=useSignContract();const releaseMainnet=useReleaseFunds();
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetContractQueryKey(id)});qc.invalidateQueries({queryKey:getGetTestnetWalletQueryKey()});qc.invalidateQueries({queryKey:getListContractsQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardSummaryQueryKey()});qc.invalidateQueries({queryKey:getListActivityQueryKey()})};
  const pi=usePiPayment(refresh);
  const [actionError,setActionError]=useState('');const [releaseNotice,setReleaseNotice]=useState('');const [delivery,setDelivery]=useState<Record<string,string>>({});const [documentHash,setDocumentHash]=useState('');const [consent,setConsent]=useState(false);
  const data=contract.data;const info=data?contractInfo(data):null;
  const currentAccountId = piAccountId ?? user?.id ?? null;
  const role=info?.buyerId&&currentAccountId===info.buyerId?'buyer':info?.sellerId&&currentAccountId===info.sellerId?'seller':'unknown';
  const pipeline=info?.pipeline&&fields[info.pipeline]?info.pipeline:null;
  const fund=async()=>{if(!data||role!=='buyer'||data.currency!=='PI'||pi.state!=='ready')return;setActionError('');try{const issued=await intent.mutateAsync({id});if(issued.contractId!==id||!Number.isFinite(issued.amount)||issued.amount<=0||issued.metadata.contractId!==id)throw new Error('Invalid server intent');await pi.pay(issued)}catch{setActionError(t('escrow.piPaymentFailed'))}};
  const runMainnetRelease=()=>{if(!data||PI_SANDBOX||data.status!=='in_delivery'||role!=='buyer')return;const message=direction==='rtl'?'سيتم تنفيذ تحويل Pi حقيقي على Mainnet وفق المبلغ والرسوم المحددة. لا يمكن التراجع عنه بعد التأكيد. هل تريد المتابعة؟':'This will execute a real Pi Mainnet transfer using the contract amount and configured fees. It cannot be reversed after confirmation. Continue?';if(!window.confirm(message))return;setReleaseNotice('');releaseMainnet.mutate({id},{onSuccess:(result)=>{refresh();if('payoutIntentId'in result)setReleaseNotice(direction==='rtl'?'تم تسجيل التحويل للتحقق؛ راجع حالة العقد قبل إعادة المحاولة.':'The payout is awaiting confirmation. Check the contract status before retrying.')},onError:()=>{refresh();setReleaseNotice(direction==='rtl'?'تعذر تأكيد التحويل. راجع حالة العقد وسجل المدفوعات قبل إعادة المحاولة.':'The transfer could not be confirmed. Check the contract and payout history before retrying.')}})};
  const submitDelivery=(e:FormEvent)=>{e.preventDefault();if(!pipeline||role!=='seller')return;const payload:DeliveryInput={};for(const field of fields[pipeline]){const text=delivery[field.key]??'';if(!text.trim())continue;if(field.key==='digitalLinks'||field.key==='goals')payload[field.key]=text.split('\n').map(s=>s.trim()).filter(Boolean);else if(field.key!=='filePaths'&&field.key!=='eSignatures')payload[field.key]=text.trim()}deliver.mutate({id,data:payload},{onSuccess:refresh})};
  if(contract.isLoading)return <div className="space-y-5"><div className="skeleton h-14 w-2/3 rounded"/><div className="skeleton h-[500px] rounded-xl"/></div>;
  if(contract.isError||!data)return <div className="rounded-xl border border-[#523830] p-8">{t('errors.notFound')} <button onClick={()=>contract.refetch()} data-testid="button-retry-contract" className="ms-4 text-[#1DE9B6]">{t('common.retry')}</button></div>;
  return <div className="mx-auto max-w-6xl animate-rise-in"><Link href="/" className="inline-flex items-center gap-2 text-xs text-[#91a997]" data-testid="link-back-contract"><ArrowLeft size={14}/>{t('contractWizard.backToOverview')}</Link><div className="mt-7 flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#1DE9B6]">{data.reference}</p><h1 className="mt-3 font-['Syne'] text-4xl font-semibold">{data.title}<span className="text-[#00C853]">.</span></h1><p className="mt-3 text-sm text-[#9bac9d]">{formatDate(data.createdAt)} / {t('contractWizard.dueDate')} {formatDate(data.dueDate)}</p></div><span className="rounded-full border border-[#25523b] bg-[#173321] px-4 py-2 text-xs text-[#1DE9B6]" data-testid="status-contract">{t(statusKeys[data.status]||'status.pending')}</span></div>
  <div className="mt-9 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-6"><section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6 sm:p-8"><div className="flex items-center gap-3"><ShieldCheck className="text-[#1DE9B6]"/><h2 className="font-['Syne'] text-xl">{t('escrow.title')}</h2></div><p className="mt-6 font-mono text-3xl" data-testid="text-contract-amount">{formatMoney(data.amount,data.currency)}</p><div className="mt-7 flex gap-2">{steps.map((s,i)=><div key={s} className={`h-1.5 flex-1 rounded-full ${steps.indexOf(data.status as typeof s)>=i?'bg-[#00C853]':'bg-[#37453b]'}`} title={t(statusKeys[s])}/>)}</div><div className="mt-5 grid gap-3 text-xs text-[#a7b9a9] sm:grid-cols-3"><p>{t('contractWizard.buyerName')}<strong className="mt-1 block text-sm text-[#e9f5ea]">{data.buyerName}</strong></p><p>{t('contractWizard.sellerName')}<strong className="mt-1 block text-sm text-[#e9f5ea]">{data.sellerName}</strong></p><p>{t('contractWizard.paymentMethod')}<strong className="mt-1 block text-sm text-[#e9f5ea]">{data.paymentMethod}</strong></p></div></section>
  <section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6 sm:p-8"><h2 className="font-['Syne'] text-xl">{t('contractWizard.choosePipeline')}</h2>{pipeline?<p className="mt-3 text-sm text-[#1DE9B6]">{t(({digital:'contractWizard.digital',shippable:'contractWizard.shippable',local_property:'contractWizard.localProperty',custom_terms:'contractWizard.customTerms'} as Record<string,TranslationKey>)[pipeline])}</p>:<p className="mt-3 text-xs text-[#e2ad85]">{t('common.notAvailable')}: {t('contractWizard.choosePipeline')}</p>}{info?.metadata&&Object.entries(info.metadata).map(([key,value])=><div key={key} className="flex justify-between gap-5 border-b border-[#2e4035] py-3 text-xs"><span className="text-[#91a995]">{key}</span><span className="max-w-[65%] break-words text-end">{typeof value==='string'?value:JSON.stringify(value)}</span></div>)}</section>
   {PI_SANDBOX ? <SandboxContractActions id={id} data={data} role={role} refresh={refresh} /> : <section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6 sm:p-8"><div className="flex items-center gap-3"><LockKeyhole className="text-[#1DE9B6]"/><h2 className="font-['Syne'] text-xl">{t('escrow.fundEscrow')}</h2></div><p className="mt-3 text-sm text-[#9faf9e]">{t('escrow.fundsHeldSecurely')}</p>{data.status==='awaiting_funding'&&<><button disabled={role!=='buyer'||data.currency!=='PI'||pi.state!=='ready'||intent.isPending} onClick={fund} className="mt-6 rounded-lg bg-[#00C853] px-5 py-3 text-sm font-bold text-[#07150b] disabled:cursor-not-allowed disabled:opacity-50" data-testid="button-pay-pi">{intent.isPending||pi.state==='paying'?t('escrow.piPaymentPending'):t('escrow.payWithPi')}</button>{(role==='unknown'||data.currency!=='PI'||pi.state==='unavailable')&&<p className="mt-3 text-xs text-[#d9b697]">{role==='unknown'?t('errors.permissionDenied'):data.currency!=='PI'?t('common.notAvailable')+': PI':t('common.notAvailable')+': Pi SDK / identity'}</p>}</>}{(actionError||pi.error)&&<p className="mt-3 text-sm text-[#ff998e]" role="alert">{actionError||pi.error}</p>}</section>}
  <section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6 sm:p-8"><div className="flex items-center gap-3"><Package className="text-[#1DE9B6]"/><h2 className="font-['Syne'] text-xl">{t('delivery.title')}</h2></div>{pipeline?<form onSubmit={submitDelivery} className="mt-6 grid gap-4 sm:grid-cols-2">{fields[pipeline].map(({key,label})=><label key={key} className="text-xs text-[#9cae9c]">{t(label)}<textarea value={delivery[key]??''} onChange={e=>setDelivery({...delivery,[key]:e.target.value})} className="mt-2 min-h-20 w-full rounded-lg border border-[#36473b] bg-[#111513] px-4 py-3 text-sm text-[#e4f2e6]" data-testid={`input-delivery-${key}`}/></label>)}<div className="sm:col-span-2"><button type="submit" disabled={deliver.isPending||role!=='seller'||!['funded','in_delivery'].includes(data.status)} className="rounded-lg bg-[#00C853] px-5 py-3 text-sm font-bold text-[#07150b] disabled:opacity-40" data-testid="button-submit-delivery">{t('delivery.submitDelivery')}</button>{role==='unknown'&&<p className="mt-2 text-xs text-[#d9b697]">{t('errors.permissionDenied')}</p>}</div></form>:<p className="mt-5 text-sm text-[#d9b697]">{t('common.notAvailable')}: {t('contractWizard.choosePipeline')}</p>}{deliver.isError&&<p className="mt-3 text-sm text-[#ff998e]">{t('errors.generic')}</p>}</section>
  <ContractEvidence id={id} canUpload={role==='seller'&&['funded','in_delivery'].includes(data.status)}/>
  {data.status==='funded'&&role==='buyer'&&<section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6"><h2 className="font-['Syne'] text-xl">{t('delivery.reviewDelivery')}</h2><p className="mt-3 text-xs text-[#a5b8a8]">{t('delivery.awaitingReview')}</p><button onClick={()=>confirmDelivery.mutate({id},{onSuccess:refresh})} disabled={confirmDelivery.isPending} className="mt-5 rounded-lg border border-[#3f6745] px-5 py-3 text-sm text-[#1DE9B6]" data-testid="button-confirm-delivery">{t('delivery.approveDelivery')}</button>{confirmDelivery.isError&&<p className="mt-3 text-xs text-[#ff9b90]">{t('errors.generic')}</p>}</section>}
    {!PI_SANDBOX&&data.status==='in_delivery'&&<section className="rounded-xl border border-[#5b4932] bg-[#1b1711] p-5 text-xs text-[#e5bd87]" data-testid="mainnet-payout-panel"><h2 className="font-semibold">{t('escrow.releasePayment')} · Pi Mainnet</h2><p className="mt-2 leading-6">{direction==='rtl'?'سيُرسل هذا الإجراء تحويل Pi حقيقيًا إلى البائع على Mainnet. التحويل المؤكد لا يمكن التراجع عنه.':'This action sends a real Pi Mainnet transfer to the seller. A confirmed transfer cannot be reversed.'}</p>{role==='buyer'&&<button onClick={runMainnetRelease} disabled={releaseMainnet.isPending} className="mt-4 rounded-lg bg-[#e5bd87] px-5 py-3 text-sm font-bold text-[#17120b] disabled:opacity-50" data-testid="button-release-mainnet">{releaseMainnet.isPending?t('common.loading'):t('escrow.releasePayment')}</button>}{releaseNotice&&<p className="mt-3 leading-6" role="alert">{releaseNotice}</p>}</section>}
  <section className="rounded-xl border border-[#324139] bg-[#1A1A1A] p-6 sm:p-8"><div className="flex items-center gap-3"><FileCheck2 className="text-[#1DE9B6]"/><h2 className="font-['Syne'] text-xl">{t('contractWizard.termsAndConditions')}</h2></div>{signatures.isError?<button onClick={()=>signatures.refetch()} className="mt-4 text-[#1DE9B6]" data-testid="button-retry-signatures">{t('common.retry')}</button>:<p className="mt-4 text-sm text-[#94aa99]">{signatures.isLoading?t('common.loading'):`${signatures.data?.length??0} ${t('contractWizard.termsAndConditions')}`}</p>}<form onSubmit={e=>{e.preventDefault();if(consent)sign.mutate({id,data:{documentHash,consent:true}},{onSuccess:()=>qc.invalidateQueries({queryKey:getListSignaturesQueryKey(id)})})}} className="mt-5 space-y-3"><label className="block text-xs text-[#a1b3a2]">SHA-256 {t('contractWizard.termsAndConditions')}<input required pattern="[a-fA-F0-9]{64}" value={documentHash} onChange={e=>setDocumentHash(e.target.value)} className="mt-2 w-full rounded-lg border border-[#36473b] bg-[#111513] p-3 font-mono text-xs" data-testid="input-document-hash"/></label><label className="flex items-start gap-3 text-xs text-[#afbdac]"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} data-testid="checkbox-sign-consent"/>{t('common.yes')} — {t('contractWizard.termsAndConditions')}</label><button disabled={!consent||sign.isPending} className="rounded-lg border border-[#3f6745] px-5 py-2.5 text-sm text-[#1DE9B6] disabled:opacity-40" data-testid="button-sign-contract">{t('common.submit')}</button></form>{sign.isError&&<p className="mt-3 text-sm text-[#ff998e]">{t('errors.generic')}</p>}</section></div>
  <aside className="space-y-4"><div className="rounded-xl border border-[#304839] bg-[#15231a] p-6"><Scale className="text-[#1DE9B6]"/><h2 className="mt-5 font-['Syne'] text-lg">{t('dashboard.awaitingAction')}</h2><p className="mt-3 text-sm leading-relaxed text-[#a5b8a5]">{data.nextAction||t(statusKeys[data.status]||'status.pending')}</p></div><Link href={`/contracts/${id}/chat`} className="flex items-center justify-between rounded-xl border border-[#35483b] bg-[#1A1A1A] p-5 text-sm hover:border-[#00C853]" data-testid="link-contract-chat"><span className="flex items-center gap-3"><MessageCircle size={18} className="text-[#1DE9B6]"/>{t('chat.title')}</span><ArrowUpRight size={16}/></Link><Link href={`/contracts/${id}/disputes`} className="flex items-center justify-between rounded-xl border border-[#35483b] bg-[#1A1A1A] p-5 text-sm hover:border-[#00C853]" data-testid="link-contract-disputes">{t('disputes.title')} ({data.disputeCount})<ArrowUpRight size={16}/></Link></aside></div></div>;
}