import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Languages, Send } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { useGetContract, useListContractMessages, useSendContractMessage, getGetContractQueryKey, getListContractMessagesQueryKey } from '@workspace/api-client-react';
import { useI18n } from '@/i18n';
export default function ContractChat(){
 const {id=''}=useParams<{id:string}>(); const {t,language}=useI18n(); const qc=useQueryClient();
 const contract=useGetContract(id,{query:{enabled:!!id,queryKey:getGetContractQueryKey(id)}});
 const messages=useListContractMessages(id,{query:{enabled:!!id,queryKey:getListContractMessagesQueryKey(id),refetchInterval:3000}});
 const send=useSendContractMessage(); const [text,setText]=useState('');const [showTranslated,setShowTranslated]=useState<Record<string,boolean>>({});
 return <div className="mx-auto max-w-4xl animate-rise-in"><Link href={`/contracts/${id}`} className="inline-flex items-center gap-2 text-xs text-[#9bb09f]" data-testid="link-back-from-chat"><ArrowLeft size={15}/>{t('common.back')}</Link><div className="mt-6 flex items-center justify-between border-b border-[#354338] pb-6"><div><p className="font-mono text-[10px] uppercase tracking-widest text-[#1DE9B6]">{contract.data?.reference}</p><h1 className="mt-2 font-['Syne'] text-3xl">{t('chat.conversation')}</h1><p className="mt-2 text-sm text-[#97a99b]">{contract.data?.title}</p></div><Languages className="text-[#1DE9B6]"/></div>
 {contract.isError||messages.isError?<div className="mt-6 rounded-xl border border-[#5b3b38] p-6 text-sm text-[#ff988d]">{t('errors.network')} <button className="ms-3 text-[#1DE9B6]" onClick={()=>{contract.refetch();messages.refetch()}} data-testid="button-retry-chat">{t('common.retry')}</button></div>:messages.isLoading?<div className="skeleton mt-7 h-96 rounded-xl"/>:<div className="mt-6 min-h-[400px] space-y-4" aria-live="polite">{messages.data?.length?messages.data.map(msg=><article key={msg.id} className="rounded-xl border border-[#314038] bg-[#1A1A1A] p-5" data-testid={`message-${msg.id}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-mono text-[10px] text-[#1DE9B6]">{msg.senderId}</span><time className="text-xs text-[#81998a]">{new Date(msg.createdAt).toLocaleString()}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{showTranslated[msg.id]&&msg.translatedText?msg.translatedText:msg.sourceText||msg.content}</p><div className="mt-3 flex items-center gap-3">{msg.translatedText?<button onClick={()=>setShowTranslated({...showTranslated,[msg.id]:!showTranslated[msg.id]})} className="text-xs text-[#1DE9B6]" data-testid={`button-translate-${msg.id}`}>{showTranslated[msg.id]?t('chat.showOriginal'):t('chat.translatedMessage')}</button>:msg.targetLanguage?<span className="text-xs text-[#879b8d]">{t('chat.translationUnavailable')}</span>:null}</div></article>):<div className="rounded-xl border border-dashed border-[#34503e] p-14 text-center text-sm text-[#9cae9f]">{t('chat.noMessages')}</div>}</div>}
 <form onSubmit={e=>{e.preventDefault();if(!text.trim())return;send.mutate({id,data:{content:text.trim(),targetLanguage:language}},{onSuccess:()=>{setText('');qc.invalidateQueries({queryKey:getListContractMessagesQueryKey(id)})}})}} className="mt-7 rounded-xl border border-[#35483b] bg-[#1A1A1A] p-4"><label className="sr-only" htmlFor="message-input">{t('chat.messagePlaceholder')}</label><textarea id="message-input" maxLength={5000} value={text} onChange={e=>setText(e.target.value)} placeholder={t('chat.messagePlaceholder')} className="h-24 w-full resize-none bg-transparent text-sm outline-none placeholder:text-[#728b79]" data-testid="input-chat-message"/><div className="flex items-center justify-between border-t border-[#2e4034] pt-4"><p className="text-xs text-[#84998a]">{t('chat.translationUnavailable')}</p><button disabled={send.isPending||!text.trim()} className="inline-flex items-center gap-2 rounded-lg bg-[#00C853] px-5 py-2.5 text-sm font-semibold text-[#07150a] disabled:opacity-50" data-testid="button-send-message"><Send size={16}/>{t('chat.sendMessage')}</button></div></form>{send.isError&&<p className="mt-3 text-sm text-[#ff998d]">{t('errors.network')}</p>}</div>;
}