import { ArrowUpRight, FileCheck2, LockKeyhole, ShieldCheck, ShieldAlert } from 'lucide-react';
import { Link } from 'wouter';
import { useGetDashboardSummary, useListActivity, useListContracts } from '@workspace/api-client-react';
import { useI18n, type TranslationKey } from '@/i18n';
import { formatDate, formatMoney } from '@/lib/escrow';
import { EscrowServiceDepositCard } from '@/components/escrow-service-deposit-card';

const statuses:Record<string,TranslationKey>={draft:'status.draft',awaiting_funding:'status.awaitingPayment',funded:'status.funded',in_delivery:'status.inProgress',completed:'status.completed',disputed:'status.disputed',resolved:'status.resolved',cancelled:'status.cancelled'};
export default function Dashboard(){
 const {t}=useI18n();const summary=useGetDashboardSummary();const contracts=useListContracts();const activity=useListActivity();
 const active=(contracts.data??[]).filter(c=>!['completed','cancelled','resolved'].includes(c.status));
 const piContracts=(contracts.data??[]).filter(c=>c.currency.toUpperCase()==='PI');
 const piTotal=piContracts.reduce((sum,c)=>sum+c.amount,0);
 const piLocked=piContracts.filter(c=>['funded','in_delivery','disputed'].includes(c.status)).reduce((sum,c)=>sum+c.amount,0);
 const piPending=piContracts.filter(c=>c.status==='in_delivery').reduce((sum,c)=>sum+c.amount,0);
 return <div className="animate-rise-in"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#1DE9B6]">PITRUST / {t('navigation.workspace')}</p><h1 className="mt-3 font-['Syne'] text-4xl font-semibold sm:text-5xl">{t('dashboard.title')}<span className="text-[#00C853]">.</span></h1><p className="mt-3 text-sm text-[#9dae9e]">{t('landing.description')}</p></div><div className="flex flex-wrap gap-3"><Link href="/marketplace" className="rounded-lg border border-[#3a6844] px-5 py-3 text-sm font-semibold text-[#1DE9B6]">{t('landing.browseMarketplace')}</Link><Link href="/contracts/new" className="rounded-lg bg-[#00C853] px-5 py-3 text-sm font-semibold text-[#08180d]" data-testid="link-dashboard-new-contract">{t('common.submit')} {t('marketplace.listing')}</Link></div></div>
 <section className="mt-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label={t('dashboard.title')}>{([
 [t('dashboard.totalValue'),contracts.data?formatMoney(piTotal,'PI'):'—',FileCheck2],
 [t('dashboard.fundsInEscrow'),contracts.data?formatMoney(piLocked,'PI'):'—',LockKeyhole],
 [t('dashboard.awaitingAction'),contracts.data?formatMoney(piPending,'PI'):'—',ShieldCheck],
 [t('disputes.title'),summary.data?.openDisputes?.toLocaleString()??'—',ShieldAlert]
 ] as const).map(([label,value,Icon],i)=><div key={i} className="rounded-xl border border-[#324238] bg-[#1A1A1A] p-6"><div className="flex items-center justify-between text-[#9aad9d]"><span className="text-xs">{label}</span><Icon size={17} className="text-[#1DE9B6]"/></div>{summary.isLoading?<div className="skeleton mt-6 h-8 w-32 rounded"/>:<p className="mt-6 font-mono text-2xl text-[#ebf5ec]">{value}</p>}</div>)}</section>
 {summary.isError&&<div className="mt-4 rounded-xl border border-[#66413b] p-4 text-sm text-[#f09b91]">{t('errors.network')} <button onClick={()=>summary.refetch()} className="ms-3 text-[#1DE9B6]" data-testid="button-retry-summary">{t('common.retry')}</button></div>}
  <EscrowServiceDepositCard/>
  <div className="mt-7 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section className="overflow-hidden rounded-xl border border-[#324238] bg-[#1A1A1A]"><header className="flex items-center justify-between border-b border-[#324238] p-5"><h2 className="font-['Syne'] text-lg">{t('dashboard.recentContracts')}</h2><Link href="/activity" className="text-xs text-[#1DE9B6]" data-testid="link-dashboard-activity">{t('dashboard.seeAll')}</Link></header>{contracts.isLoading?<div className="skeleton m-5 h-64 rounded-lg"/>:contracts.isError?<div className="p-6 text-sm text-[#f09b91]">{t('errors.network')} <button onClick={()=>contracts.refetch()} className="text-[#1DE9B6]" data-testid="button-retry-contracts">{t('common.retry')}</button></div>:!active.length?<div className="p-12 text-center"><FileCheck2 className="mx-auto text-[#1DE9B6]"/><h3 className="mt-4 font-semibold">{t('dashboard.noContracts')}</h3><p className="mt-2 text-sm text-[#9dae9e]">{t('dashboard.noContractsDescription')}</p><Link href="/marketplace" className="mt-5 inline-block text-sm text-[#1DE9B6]" data-testid="link-empty-new-contract">{t('landing.browseMarketplace')}</Link></div>:<div className="divide-y divide-[#334239]">{active.slice(0,7).map(c=><Link href={`/contracts/${c.id}`} key={c.id} className="flex flex-wrap items-center justify-between gap-4 p-5 transition-colors hover:bg-[#202a22]" data-testid={`link-contract-${c.id}`}><div><p className="text-sm font-semibold">{c.title}</p><p className="mt-1 font-mono text-[10px] text-[#91a797]">{c.reference} / {formatDate(c.dueDate)}</p></div><div className="flex items-center gap-5"><div className="text-end"><p className="font-mono text-sm">{formatMoney(c.amount,c.currency)}</p><p className="mt-1 text-xs text-[#1DE9B6]">{t(statuses[c.status]||'status.pending')}</p></div><ArrowUpRight size={16} className="text-[#1DE9B6]"/></div></Link>)}</div>}</section>
 <section className="overflow-hidden rounded-xl border border-[#324238] bg-[#1A1A1A]"><header className="flex items-center justify-between border-b border-[#324238] p-5"><h2 className="font-['Syne'] text-lg">{t('landing.recentActivity')}</h2><Link href="/activity" className="text-xs text-[#1DE9B6]" data-testid="link-all-activity">{t('landing.viewAllActivity')}</Link></header>{activity.isLoading?<div className="skeleton m-5 h-64 rounded-lg"/>:activity.isError?<div className="p-6 text-sm text-[#f09b91]">{t('errors.network')} <button onClick={()=>activity.refetch()} data-testid="button-retry-activity">{t('common.retry')}</button></div>:!activity.data?.length?<p className="p-12 text-center text-sm text-[#9dae9e]">{t('search.noResults')}</p>:<div className="divide-y divide-[#334239]">{activity.data.slice(0,6).map(a=><Link href={`/contracts/${a.contractId}`} key={a.id} className="block p-5 hover:bg-[#202a22]" data-testid={`link-dashboard-event-${a.id}`}><p className="text-sm font-semibold">{a.title}</p><p className="mt-1 line-clamp-2 text-xs text-[#9dad9f]">{a.description}</p><p className="mt-2 font-mono text-[10px] text-[#879d8d]">{new Date(a.createdAt).toLocaleString()}</p></Link>)}</div>}</section></div></div>;
}