import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Globe2, Plus, Search, Store, X } from 'lucide-react';
import { useLocation } from 'wouter';
import { getSearchListingsQueryKey, getListContractsQueryKey, useCreateListingContract, useGetMarketStats, useSearchListings, type ListingInputPipeline } from '@workspace/api-client-react';
import { useI18n } from '@/i18n';

const pipelines: ListingInputPipeline[] = ['digital','shippable','local_property','custom_terms'];
export default function Marketplace() {
  const {t} = useI18n();
  const qc = useQueryClient();
  const [,navigate] = useLocation();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<ListingInputPipeline | ''>('');
  const [selected,setSelected]=useState<string|null>(null);
  const [dueDate,setDueDate]=useState('');
  const params = {q: search || undefined, pipeline: filter || undefined};
  const listings = useSearchListings(params, {query:{queryKey:getSearchListingsQueryKey(params)}});
  const stats = useGetMarketStats();
  const createContract=useCreateListingContract();
  const labels = [t('contractWizard.digital'),t('contractWizard.shippable'),t('contractWizard.localProperty'),t('contractWizard.customTerms')];
  return <div className="animate-rise-in"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#1DE9B6]">01 / {t('navigation.marketplace')}</p><h1 className="mt-3 font-['Syne'] text-4xl font-semibold tracking-tight sm:text-5xl">{t('marketplace.title')}<span className="text-[#00C853]">.</span></h1><p className="mt-3 max-w-xl text-sm text-[#9caea3]">{t('marketplace.subtitle')}</p></div><button onClick={() => navigate('/contracts/new')} className="flex items-center gap-2 rounded-lg bg-[#00C853] px-5 py-3 text-sm font-semibold text-[#09180d]" data-testid="button-new-listing"><Plus size={16}/>{t('common.submit')} {t('marketplace.listing')}</button></div>
  <div className="mt-9 grid gap-4 border-y border-[#2b3830] py-5 sm:grid-cols-3">{[[t('marketplace.listing'), stats.data?.listings],[t('navigation.contracts'),stats.data?.contracts],[t('dashboard.totalValue'),stats.data?.escrowVolume]].map(([label,value],i)=><div key={i} className="border-s border-[#2e4034] ps-4"><p className="text-xs text-[#85998a]">{label}</p><p className="mt-2 font-mono text-2xl text-[#e7f6eb]">{stats.isError ? '—' : stats.isLoading ? '···' : typeof value === 'number' ? `${value.toLocaleString()}${i===2?' PI':''}` : '—'}</p></div>)}</div>{stats.isError && <button onClick={() => stats.refetch()} className="mt-2 text-xs text-[#1DE9B6]" data-testid="button-retry-market-stats">{t('errors.network')} {t('common.retry')}</button>}
  <div className="mt-8 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-lg border border-[#344037] bg-[#1A1A1A] px-4"><Search size={17} className="text-[#8fa396]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('search.placeholder')} className="h-12 w-full bg-transparent text-sm outline-none" data-testid="input-search-listings"/></label><select className="h-12 rounded-lg border border-[#344037] bg-[#1A1A1A] px-4 text-sm" value={filter} onChange={e=>setFilter(e.target.value as ListingInputPipeline | '')} data-testid="select-listing-pipeline"><option value="">{t('common.all')}</option>{pipelines.map((p,i)=><option key={p} value={p}>{labels[i]}</option>)}</select></div>
  {listings.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="skeleton h-52 rounded-xl"/>)}</div> : listings.isError ? <div className="mt-8 rounded-xl border border-[#523b37] bg-[#241b1a] p-6">{t('errors.network')} <button onClick={()=>listings.refetch()} className="ms-3 text-[#1DE9B6]" data-testid="button-retry-listings">{t('common.retry')}</button></div> : !listings.data?.length ? <div className="mt-8 rounded-xl border border-dashed border-[#34503e] bg-[#142018] px-8 py-16 text-center"><Store className="mx-auto text-[#1DE9B6]" size={32}/><h2 className="mt-4 font-['Syne'] text-xl">{t('marketplace.noListings')}</h2></div> : <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{listings.data.map(item=><article key={item.id} className="group flex min-h-64 flex-col justify-between rounded-xl border border-[#2b3a30] bg-[#1A1A1A] p-6 transition-colors hover:border-[#00C853]" data-testid={`listing-${item.id}`}><div><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-widest text-[#1DE9B6]">{labels[pipelines.indexOf(item.pipeline)]}</span><Globe2 size={16} className="text-[#718c7a]"/></div><h2 className="mt-5 font-['Syne'] text-xl font-semibold">{item.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-[#9baa9e]">{item.description}</p></div><div className="mt-7 flex items-center justify-between border-t border-[#334038] pt-4"><span className="font-mono text-lg">{item.amount.toLocaleString()} <small className="text-xs text-[#92a999]">{item.currency}</small></span><button onClick={()=>setSelected(item.id)} className="text-[#1DE9B6]" disabled={item.currency!=='PI'} data-testid={`button-listing-contract-${item.id}`} aria-label={t('navigation.createContract')} title={item.currency!=='PI'?t('common.notAvailable'):undefined}><ArrowRight size={20}/></button></div></article>)}</div>}
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#080d0a]/85 p-4"><form onSubmit={e=>{e.preventDefault();createContract.mutate({id:selected,data:{dueDate}},{onSuccess:contract=>{qc.invalidateQueries({queryKey:getListContractsQueryKey()});navigate(`/contracts/${contract.id}`)}})}} className="w-full max-w-md rounded-xl border border-[#36503b] bg-[#1A1A1A] p-6"><div className="flex justify-between"><h2 className="font-['Syne'] text-2xl">{t('navigation.createContract')}</h2><button type="button" onClick={()=>setSelected(null)} aria-label={t('common.close')} data-testid="button-close-listing-contract"><X size={20}/></button></div><p className="mt-3 text-sm text-[#9caf9f]">{t('contractWizard.description')}</p><label className="mt-6 block text-xs">{t('contractWizard.dueDate')}<input required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="mt-2 w-full rounded-lg border border-[#35473a] bg-[#111513] p-3 text-sm" data-testid="input-listing-due-date"/></label>{createContract.isError&&<p className="mt-3 text-sm text-[#ff9c90]">{t('errors.generic')}</p>}<button disabled={createContract.isPending} className="mt-6 w-full rounded-lg bg-[#00C853] py-3 font-semibold text-[#08130c]" data-testid="button-create-listing-contract">{createContract.isPending?t('common.loading'):t('contractWizard.createAgreement')}</button></form></div>}
  </div>;
}